// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeaderID    int64          `json:"leader_id"`
}

type Task struct {
	ID          int64          `json:"id"`
	ProjectID   int64          `json:"project_id"`
	MantainerID int64          `json:"mantainer_id"`
	Status      int64          `json:"status"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Invite   string `json:"invite"`
	Username string `json:"username"`
	Password string `json:"password"`
}
