// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LeaderID    int64          `json:"leader_id"`
}

type Task struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	StartedAt   sql.NullTime   `json:"started_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	FinishedAt  sql.NullTime   `json:"finished_at"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UsersProject struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	ProjectID int64 `json:"project_id"`
}

type UsersTask struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	TaskID int64 `json:"task_id"`
}
